modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License v3.0"
[[mods]]
modId="curseoftheabyss"
version="1.0.0.1"
displayName="Curse of the Abyss Reborn"
logoFile="curseoftheabyss.png"
description=''''''
[[dependencies.curseoftheabyss]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseoftheabyss]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseoftheabyss]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.2-5.0.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseoftheabyss]]
    modId="sanitydim"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseoftheabyss]]
    modId="thirst"
    mandatory=false
    versionRange="[1.3.2,)"
    ordering="NONE"
    side="BOTH"