modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="curseoftheabyss"
version="1.0.0"
displayName="Curse of the Abyss"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="chizh, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.curseoftheabyss]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.curseoftheabyss]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.curseoftheabyss]]
modId="curios_api"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.curseoftheabyss.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration