modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="curseoftheabyss"
version="1.0.0.1"
displayName="Curse of the Abyss: The Mystery of the Depths"
displayURL="https://esmods.com"
credits="Created by Auranite Studio with support Samuelchik"
authors="Auranite Studio"
description="This mod adds a new level of danger to Minecraft in deep caves (below the Y=0 level).  The deeper you go down, the stronger the curse will be when you try to climb up."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.curseoftheabyss]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.curseoftheabyss]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




[[mixins]]
    config="mixins.curseoftheabyss.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration